# Generated by Django 4.1.1 on 2022-09-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='room_name',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
